# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1746e4c679bcc7b4a03a2a5187771729"
name = "Evergreen Apparel Co"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_checkouts,read_checkouts,read_online_store_navigation,write_online_store_navigation,read_payment_customizations,write_payment_customizations,read_product_feeds,write_product_feeds,read_product_listings,write_product_listings,read_products,write_products,read_purchase_options,write_purchase_options,read_returns,write_returns,read_shipping,write_shipping,read_shopify_payments_accounts,read_shopify_payments_payouts,read_shopify_payments_bank_accounts,read_store_credit_account_transactions,read_store_credit_accounts,read_themes,write_themes,unauthenticated_write_checkouts,unauthenticated_read_checkouts,unauthenticated_read_customer_tags,unauthenticated_read_product_inventory,unauthenticated_read_product_listings,unauthenticated_read_product_tags,unauthenticated_read_content"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://webhook.site/65272445-30a5-473c-aac2-fc885d7c99aa" ]
